#!/bin/sh
SERVER=$1
TOKEN=$2

if [ -z "${SERVER}" ] || [ -z "${TOKEN}" ]; then
    echo "Usage: $0 <SERVER> <TOKEN>"
    exit 1
fi

HOST=$(echo "$SERVER" | sed 's|^https://||' | sed 's|/.*$||')
CRED_FILE="${HOME}/.git-credentials.$HOST"

git config --global credential.$SERVER.helper "store --file $CRED_FILE"

cat << EOF | git credential approve
protocol=https
host=$HOST
username=_
password=$TOKEN
EOF
