#!/bin/sh
SERVER=$1
USER=$2
PASS=$3

if [ -z "${SERVER}" ] || [ -z "${USER}" ] || [ -z "${PASS}" ]; then
    echo "Usage: $0 <SERVER> <USER> <PASS>"
    exit 1
fi

HOST=$(echo "$SERVER" | sed 's|^https://||' | sed 's|/.*$||')
CRED_FILE="${HOME}/.git-credentials.$HOST"

git config --global credential.$SERVER.helper "store --file $CRED_FILE"

cat << EOF | git credential approve
protocol=https
host=$HOST
username=$USER
password=$PASS
EOF
