services:
  github-runner:
    image: ghcr.io/actions/actions-runner:latest
    restart: always
    command: ./run.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/config
      - workspace:/home/runner/_work
    configs:
      - source: entrypoint.sh
        target: /entrypoint.sh
        mode: 0755
    entrypoint: /entrypoint.sh


configs:
  entrypoint.sh:
    content: |
      #!/bin/bash
      set -e
      cp -a /config/.runner .
      cp -a /config/.path .
      cp -a /config/.credentials .
      cp -a /config/.credentials_rsaparams .
      exec "$@"


volumes:
  config:
  workspace:
